---
title: "Hypothesis_testing"
author: "Team Dataverse(Yashwant, Manoj, Sai and Sravya)"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r results=T}
#Loading libraries
library(ezids)
library(ggplot2)
```



```{r}
car_data = data.frame(read.csv('cars.csv'))
str(car_data)
```

Data cleaning

```{r results=T}
car_data$transmission = as.factor(car_data$transmission)
car_data$engine_fuel = as.factor(car_data$engine_fuel)
car_data$engine_has_gas = as.factor(car_data$engine_has_gas)
car_data$engine_type = as.factor(car_data$engine_type)
car_data$body_type = as.factor(car_data$body_type)
car_data$has_warranty = as.factor(car_data$has_warranty)
car_data$state = as.factor(car_data$state)
car_data$drivetrain = as.factor(car_data$drivetrain)
car_data$is_exchangeable = as.factor(car_data$is_exchangeable)
car_data$location_region = as.factor(car_data$location_region)
```



```{r results=T}
#car_data$year_produced <- strptime(car_data$year_produced, "%Y")
```

```{r results=T}
feature_cols <- c(20:29)
car_data[feature_cols] <- lapply(car_data[feature_cols],factor)
str(car_data)
```

```{r results=T}
sapply(car_data, function(x) sum(is.na(x)))
```


```{r results=T}
car_data$engine_capacity[is.na(car_data$engine_capacity)] <- 0
mean(car_data$engine_capacity)
median(car_data$engine_capacity)
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
s <- getmode(car_data$engine_capacity)
s
```

```{r results=T}
car_data$engine_capacity[is.na(car_data$engine_capacity)] <- mean(car_data$engine_capacity,na.rm = TRUE)
sapply(car_data, function(x) sum(is.na(x)))
```

## Unknown features(feature0 to feature9)

Is feature_0 impacting the average car price?

```{r}
with_feature_0<-subset(car_data,feature_0 == 'True')
without_feature_0<-subset(car_data,feature_0 == 'False')
```

```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature0 = t.test(x=with_feature_0$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature0


Hypothesis_test_price_without_feature0 = t.test(x=without_feature_0$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature0
```

Is feature_1 impacting the average car price?

```{r}
with_feature_1<-subset(car_data,feature_1 == 'True')
without_feature_1<-subset(car_data,feature_1 == 'False')
```


```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature1 = t.test(x=with_feature_1$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature1


Hypothesis_test_price_without_feature1 = t.test(x=without_feature_1$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature1
```

Is feature_2 impacting the average car price?

```{r}
with_feature_2<-subset(car_data,feature_2 == 'True')
without_feature_2<-subset(car_data,feature_2 == 'False')
```


```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature2 = t.test(x=with_feature_2$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature2


Hypothesis_test_price_without_feature2 = t.test(x=without_feature_2$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature2
```
```{r}
with_feature_3<-subset(car_data,feature_3 == 'True')
without_feature_3<-subset(car_data,feature_3 == 'False')
```


```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature3 = t.test(x=with_feature_3$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature3


Hypothesis_test_price_without_feature3 = t.test(x=without_feature_3$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature3
```

```{r}
with_feature_4<-subset(car_data,feature_4 == 'True')
without_feature_4<-subset(car_data,feature_4 == 'False')
```

```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature4 = t.test(x=with_feature_4$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature4


Hypothesis_test_price_without_feature4 = t.test(x=without_feature_4$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature4
```

```{r}
with_feature_5<-subset(car_data,feature_5 == 'True')
without_feature_5<-subset(car_data,feature_5 == 'False')
```


```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature5 = t.test(x=with_feature_5$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature5


Hypothesis_test_price_without_feature5 = t.test(x=without_feature_5$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature5
```

```{r}
with_feature_6<-subset(car_data,feature_6 == 'True')
without_feature_6<-subset(car_data,feature_6 == 'False')
```


```{r results=T}
#mean of GRE score
mean_price = mean(car_data$price_usd) #Mean GRE based on full data
mean_price
#for GRE score of admitted students 

Hypothesis_test_price_with_feature6 = t.test(x=with_feature_6$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_with_feature6


Hypothesis_test_price_without_feature6 = t.test(x=without_feature_6$price_usd,mu = mean_price ,conf.level = 0.95) 
#default conf.level = 0.95
Hypothesis_test_price_without_feature6
```



## Chi square test of independence on Year of manufacture and price

Car resale prices are dependent on the year of manufacture?

```{r}
p_usd.intrv = cut(car_data$price_usd, c(0,10000,20000,30000,40000,50000))
year.intrv = cut(car_data$year_produced, c(1940,1950,1960,1970,1980,1990,2000,2010,2020))
lists <- list(price_intvl = as.character(p_usd.intrv),yr_interval = as.character(year.intrv))
df <- as.data.frame(do.call(cbind, lists))
conTable = table(df)
print(conTable)
```

```{r}
df
```

```{r results=T}
chitest = chisq.test(conTable)
chitest
```

